export const PROFILE_DATA = 'PROFILE_DATA';

export const SERVICE_PROVIDER_DATA = 'SERVICE_PROVIDER_DATA';
export const SERVICE_PROVIDER_DATA_SUCCESS = 'SERVICE_PROVIDER_DATA_SUCCESS';
export const SERVICE_PROVIDER_DATA_ERROR = 'SERVICE_PROVIDER_DATA_ERROR';