export const PROFILE_DATA = "PROFILE_DATA";
export const PROFILE_LOGGED_IN_MODULE = "PROFILE_LOGGED_IN_MODULE";
export const GUEST_USER = "GUEST_USER";

export const SERVICE_PROVIDER_DATA = "SERVICE_PROVIDER_DATA";
export const SERVICE_PROVIDER_DATA_SUCCESS = "SERVICE_PROVIDER_DATA_SUCCESS";
export const SERVICE_PROVIDER_DATA_ERROR = "SERVICE_PROVIDER_DATA_ERROR";

export const SERVICE_PROVIDER_ROLE = "SERVICE_PROVIDER_ROLE";
export const SERVICE_PROVIDER_ROLE_SUCCESS = "SERVICE_PROVIDER_ROLE_SUCCESS";
export const SERVICE_PROVIDER_ROLE_ERROR = "SERVICE_PROVIDER_ROLE_ERROR";
export const REFRESH_USER_DATA = "REFRESH_USER_DATA"
export const REFRESH_ACTIVITY_DATA = "REFRESH_ACTIVITY_DATA"
