export const BREEDS = [
  { id: 1, label: "Affenpinscher" },
  { id: 2, label: "Afghan Hound" },
  { id: 3, label: "Aidi" },
  { id: 4, label: "Airedale Terrier" },
  { id: 5, label: "Akbash Dog" },
  { id: 6, label: "Akita" },
  { id: 7, label: "Alano Español" },
  { id: 8, label: "Alaskan Klee Kai" },
  { id: 9, label: "Alaskan Malamute" },
  { id: 10, label: "Alpine Dachsbracke" },
  { id: 11, label: "Alpine Spaniel" },
  { id: 12, label: "American Bulldog" },
  { id: 13, label: "American Cocker Spaniel" },
  { id: 14, label: "American Eskimo Dog" },
  { id: 15, label: "American Foxhound" },
  { id: 16, label: "American Hairless Terrier" },
  { id: 17, label: "American Pit Bull Terrier" },
  { id: 18, label: "American Staffordshire Terrier" },
  { id: 19, label: "American Water Spaniel" },
  { id: 20, label: "Anglo-Français de Petite Vénerie" },
  { id: 21, label: "Appenzeller Sennenhund" },
  { id: 22, label: "Ariege Pointer" },
  { id: 23, label: "Ariegeois" },
  { id: 24, label: "Armant" },
  { id: 25, label: "Armenian Gampr dog" },
  { id: 26, label: "Artois Hound" },
  { id: 27, label: "Australian Cattle Dog" },
  { id: 28, label: "Australian Kelpie" },
  { id: 29, label: "Australian Shepherd" },
  { id: 30, label: "Australian Silky Terrier" },
  { id: 31, label: "Australian Stumpy Tail Cattle Dog" },
  { id: 32, label: "Australian Terrier" },
  { id: 33, label: "Azawakh" },
  { id: 34, label: "Bakharwal Dog" },
  { id: 35, label: "Barbet" },
  { id: 36, label: "Basenji" },
  { id: 37, label: "Basque Shepherd Dog" },
  { id: 38, label: "Basset Artésien Normand" },
  { id: 39, label: "Basset Bleu de Gascogne" },
  { id: 40, label: "Basset Fauve de Bretagne" },
  { id: 41, label: "Basset Hound" },
  { id: 42, label: "Bavarian Mountain Hound" },
  { id: 43, label: "Beagle" },
  { id: 44, label: "Beagle-Harrier" },
  { id: 45, label: "Bearded Collie" },
  { id: 46, label: "Beauceron" },
  { id: 47, label: "Bedlington Terrier" },
  { id: 48, label: "Belgian Shepherd Dog (Groenendael)" },
  { id: 49, label: "Belgian Shepherd Dog (Laekenois)" },
  { id: 50, label: "Belgian Shepherd Dog (Malinois)" },
  { id: 51, label: "Bergamasco Shepherd" },
  { id: 52, label: "Berger Blanc Suisse" },
  { id: 53, label: "Berger Picard" },
  { id: 54, label: "Berner Laufhund" },
  { id: 55, label: "Bernese Mountain Dog" },
  { id: 56, label: "Billy" },
  { id: 57, label: "Black and Tan Coonhound" },
  { id: 58, label: "Black and Tan Virginia Foxhound" },
  { id: 59, label: "Black Norwegian Elkhound" },
  { id: 60, label: "Black Russian Terrier" },
  { id: 61, label: "Bloodhound" },
  { id: 62, label: "Blue Lacy" },
  { id: 63, label: "Blue Paul Terrier" },
  { id: 64, label: "Boerboel" },
  { id: 65, label: "Bohemian Shepherd" },
  { id: 66, label: "Bolognese" },
  { id: 67, label: "Border Collie" },
  { id: 68, label: "Border Terrier" },
  { id: 69, label: "Borzoi" },
  { id: 70, label: "Boston Terrier" },
  { id: 71, label: "Bouvier des Ardennes" },
  { id: 72, label: "Bouvier des Flandres" },
  { id: 73, label: "Boxer" },
  { id: 74, label: "Boykin Spaniel" },
  { id: 75, label: "Bracco Italiano" },
  { id: 76, label: "Braque d'Auvergne" },
  { id: 77, label: "Braque du Bourbonnais" },
  { id: 78, label: "Braque du Puy" },
  { id: 79, label: "Braque Francais" },
  { id: 80, label: "Braque Saint-Germain" },
  { id: 81, label: "Brazilian Terrier" },
  { id: 82, label: "Briard" },
  { id: 83, label: "Briquet Griffon Vendéen" },
  { id: 84, label: "Brittany" },
  { id: 85, label: "Broholmer" },
  { id: 86, label: "Bruno Jura Hound" },
  { id: 87, label: "Bucovina Shepherd Dog" },
  { id: 88, label: "Bull and Terrier" },
  { id: 89, label: "Bull Terrier (Miniature)" },
  { id: 90, label: "Bull Terrier" },
  { id: 91, label: "Bulldog" },
  { id: 92, label: "Bullenbeisser" },
  { id: 93, label: "Bullmastiff" },
  { id: 94, label: "Bully Kutta" },
  { id: 95, label: "Burgos Pointer" },
  { id: 96, label: "Cairn Terrier" },
  { id: 97, label: "Canaan Dog" },
  { id: 98, label: "Canadian Eskimo Dog" },
  { id: 99, label: "Cane Corso" },
  { id: 100, label: "Cardigan Welsh Corgi" },
  { id: 101, label: "Carolina Dog" },
  { id: 102, label: "Carpathian Shepherd Dog" },
  { id: 103, label: "Catahoula Cur" },
  { id: 104, label: "Catalan Sheepdog" },
  { id: 105, label: "Caucasian Shepherd Dog" },
  { id: 106, label: "Cavalier King Charles Spaniel" },
  { id: 107, label: "Central Asian Shepherd Dog" },
  { id: 108, label: "Cesky Fousek" },
  { id: 109, label: "Cesky Terrier" },
  { id: 110, label: "Chesapeake Bay Retriever" },
  { id: 111, label: "Chien Français Blanc et Noir" },
  { id: 112, label: "Chien Français Blanc et Orange" },
  { id: 113, label: "Chien Français Tricolore" },
  { id: 114, label: "Chien-gris" },
  { id: 115, label: "Chihuahua" },
  { id: 116, label: "Chilean Fox Terrier" },
  { id: 117, label: "Chinese Chongqing Dog" },
  { id: 118, label: "Chinese Crested Dog" },
  { id: 119, label: "Chinese Imperial Dog" },
  { id: 120, label: "Chinook" },
  { id: 121, label: "Chippiparai" },
  { id: 122, label: "Chow Chow" },
  { id: 123, label: "Cierny Sery" },
  { id: 124, label: "Cimarrón Uruguayo" },
  { id: 125, label: "Cirneco dell'Etna" },
  { id: 126, label: "Clumber Spaniel" },
  { id: 127, label: "Combai" },
  { id: 128, label: "Cordoba Fighting Dog" },
  { id: 129, label: "Coton de Tulear" },
  { id: 130, label: "Cretan Hound" },
  { id: 131, label: "Croatian Sheepdog" },
  { id: 132, label: "Cumberland Sheepdog" },
  { id: 133, label: "Curly Coated Retriever" },
  { id: 134, label: "Cursinu" },
  { id: 135, label: "Cão da Serra de Aires" },
  { id: 136, label: "Cão de Castro Laboreiro" },
  { id: 137, label: "Cão Fila de São Miguel" },
  { id: 138, label: "Dachshund" },
  { id: 139, label: "Dalmatian" },
  { id: 140, label: "Dandie Dinmont Terrier" },
  { id: 141, label: "Danish Swedish Farmdog" },
  { id: 142, label: "Deutsche Bracke" },
  { id: 143, label: "Doberman Pinscher" },
  { id: 144, label: "Dogo Argentino" },
  { id: 145, label: "Dogo Cubano" },
  { id: 146, label: "Dogue de Bordeaux" },
  { id: 147, label: "Drentse Patrijshond" },
  { id: 148, label: "Drever" },
  { id: 149, label: "Dunker" },
  { id: 150, label: "Dutch Shepherd Dog" },
  { id: 151, label: "Dutch Smoushond" },
  { id: 152, label: "East Siberian Laika" },
  { id: 153, label: "East-European Shepherd" },
  { id: 154, label: "Elo" },
  { id: 155, label: "English Cocker Spaniel" },
  { id: 156, label: "English Foxhound" },
  { id: 157, label: "English Mastiff" },
  { id: 158, label: "English Setter" },
  { id: 159, label: "English Shepherd" },
  { id: 160, label: "English Springer Spaniel" },
  { id: 161, label: "English Toy Terrier (Black &amp; Tan)" },
  { id: 162, label: "English Water Spaniel" },
  { id: 163, label: "English White Terrier" },
  { id: 164, label: "Entlebucher Mountain Dog" },
  { id: 165, label: "Estonian Hound" },
  { id: 166, label: "Estrela Mountain Dog" },
  { id: 167, label: "Eurasier" },
  { id: 168, label: "Field Spaniel" },
  { id: 169, label: "Fila Brasileiro" },
  { id: 170, label: "Finnish Hound" },
  { id: 171, label: "Finnish Lapphund" },
  { id: 172, label: "Finnish Spitz" },
  { id: 173, label: "Flat-Coated Retriever" },
  { id: 174, label: "Formosan Mountain Dog" },
  { id: 175, label: "Fox Terrier (Smooth)" },
  { id: 176, label: "French Bulldog" },
  { id: 177, label: "French Spaniel" },
  { id: 178, label: "Galgo Español" },
  { id: 179, label: "Gascon Saintongeois" },
  { id: 180, label: "German Longhaired Pointer" },
  { id: 181, label: "German Pinscher" },
  { id: 182, label: "German Shepherd" },
  { id: 183, label: "German Shorthaired Pointer" },
  { id: 184, label: "German Spaniel" },
  { id: 185, label: "German Spitz" },
  { id: 186, label: "German Wirehaired Pointer" },
  { id: 187, label: "Giant Schnauzer" },
  { id: 188, label: "Glen of Imaal Terrier" },
  { id: 189, label: "Golden Retriever" },
  { id: 190, label: "Gordon Setter" },
  { id: 191, label: "Gran Mastín de Borínquen" },
  { id: 192, label: "Grand Anglo-Français Blanc et Noir" },
  { id: 193, label: "Grand Anglo-Français Blanc et Orange" },
  { id: 194, label: "Grand Anglo-Français Tricolore" },
  { id: 195, label: "Grand Basset Griffon Vendéen" },
  { id: 196, label: "Grand Bleu de Gascogne" },
  { id: 197, label: "Grand Griffon Vendéen" },
  { id: 198, label: "Great Dane" },
  { id: 199, label: "Great Pyrenees" },
  { id: 200, label: "Greater Swiss Mountain Dog" },
  { id: 201, label: "Greek Harehound" },
  { id: 202, label: "Greenland Dog" },
  { id: 203, label: "Greyhound" },
  { id: 204, label: "Griffon Bleu de Gascogne" },
  { id: 205, label: "Griffon Bruxellois" },
  { id: 206, label: "Griffon Fauve de Bretagne" },
  { id: 207, label: "Griffon Nivernais" },
  { id: 208, label: "Hamiltonstövare" },
  { id: 209, label: "Hanover Hound" },
  { id: 210, label: "Hare Indian Dog" },
  { id: 211, label: "Harrier" },
  { id: 212, label: "Havanese" },
  { id: 213, label: "Hawaiian Poi Dog" },
  { id: 214, label: "Himalayan Sheepdog" },
  { id: 215, label: "Hokkaido" },
  { id: 216, label: "Hovawart" },
  { id: 217, label: "Huntaway" },
  { id: 218, label: "Hygenhund" },
  { id: 219, label: "Ibizan Hound" },
  { id: 220, label: "Icelandic Sheepdog" },
  { id: 221, label: "Indian pariah dog" },
  { id: 222, label: "Indian Spitz" },
  { id: 223, label: "Irish Red and White Setter" },
  { id: 224, label: "Irish Setter" },
  { id: 225, label: "Irish Terrier" },
  { id: 226, label: "Irish Water Spaniel" },
  { id: 227, label: "Irish Wolfhound" },
  { id: 228, label: "Istrian Coarse-haired Hound" },
  { id: 229, label: "Istrian Shorthaired Hound" },
  { id: 230, label: "Italian Greyhound" },
  { id: 231, label: "Jack Russell Terrier" },
  { id: 232, label: "Jagdterrier" },
  { id: 233, label: "Jämthund" },
  { id: 234, label: "Kai Ken" },
  { id: 235, label: "Kaikadi" },
  { id: 236, label: "Kanni" },
  { id: 237, label: "Karelian Bear Dog" },
  { id: 238, label: "Karst Shepherd" },
  { id: 239, label: "Keeshond" },
  { id: 240, label: "Kerry Beagle" },
  { id: 241, label: "Kerry Blue Terrier" },
  { id: 242, label: "King Charles Spaniel" },
  { id: 243, label: "King Shepherd" },
  { id: 244, label: "Kintamani" },
  { id: 245, label: "Kishu" },
  { id: 246, label: "Komondor" },
  { id: 247, label: "Kooikerhondje" },
  { id: 248, label: "Koolie" },
  { id: 249, label: "Korean Jindo Dog" },
  { id: 250, label: "Kromfohrländer" },
  { id: 251, label: "Kumaon Mastiff" },
  { id: 252, label: "Kurī" },
  { id: 253, label: "Kuvasz" },
  { id: 254, label: "Kyi-Leo" },
  { id: 255, label: "Labrador Husky" },
  { id: 256, label: "Labrador Retriever" },
  { id: 257, label: "Lagotto Romagnolo" },
  { id: 258, label: "Lakeland Terrier" },
  { id: 259, label: "Lancashire Heeler" },
  { id: 260, label: "Landseer" },
  { id: 261, label: "Lapponian Herder" },
  { id: 262, label: "Large Münsterländer" },
  { id: 263, label: "Leonberger" },
  { id: 264, label: "Lhasa Apso" },
  { id: 265, label: "Lithuanian Hound" },
  { id: 266, label: "Longhaired Whippet" },
  { id: 267, label: "Löwchen" },
  { id: 268, label: "Mahratta Greyhound" },
  { id: 269, label: "Maltese" },
  { id: 270, label: "Manchester Terrier" },
  { id: 271, label: "Maremma Sheepdog" },
  { id: 272, label: "McNab" },
  { id: 273, label: "Mexican Hairless Dog" },
  { id: 274, label: "Miniature American Shepherd" },
  { id: 275, label: "Miniature Australian Shepherd" },
  { id: 276, label: "Miniature Fox Terrier" },
  { id: 277, label: "Miniature Pinscher" },
  { id: 278, label: "Miniature Schnauzer" },
  { id: 279, label: "Miniature Shar Pei" },
  { id: 280, label: "Molossus" },
  { id: 281, label: "Montenegrin Mountain Hound" },
  { id: 282, label: "Moscow Watchdog" },
  { id: 283, label: "Moscow Water Dog" },
  { id: 284, label: "Mountain Cur" },
  { id: 285, label: "Mucuchies" },
  { id: 286, label: "Mudhol Hound" },
  { id: 287, label: "Mudi" },
  { id: 288, label: "Neapolitan Mastiff" },
  { id: 289, label: "New Zealand Heading Dog" },
  { id: 290, label: "Newfoundland" },
  { id: 291, label: "Norfolk Spaniel" },
  { id: 292, label: "Norfolk Terrier" },
  { id: 293, label: "Norrbottenspets" },
  { id: 294, label: "North Country Beagle" },
  { id: 295, label: "Northern Inuit Dog" },
  { id: 296, label: "Norwegian Buhund" },
  { id: 297, label: "Norwegian Elkhound" },
  { id: 298, label: "Norwegian Lundehund" },
  { id: 299, label: "Norwich Terrier" },
  { id: 300, label: "Old Croatian Sighthound" },
  { id: 301, label: "Old Danish Pointer" },
  { id: 302, label: "Old English Sheepdog" },
  { id: 303, label: "Old English Terrier" },
  { id: 304, label: "Old German Shepherd Dog" },
  { id: 305, label: "Olde English Bulldogge" },
  { id: 306, label: "Otterhound" },
  { id: 307, label: "Pachon Navarro" },
  { id: 308, label: "Paisley Terrier" },
  { id: 309, label: "Pandikona" },
  { id: 310, label: "Papillon" },
  { id: 311, label: "Parson Russell Terrier" },
  { id: 312, label: "Patterdale Terrier" },
  { id: 313, label: "Pekingese" },
  { id: 314, label: "Pembroke Welsh Corgi" },
  { id: 315, label: "Perro de Presa Canario" },
  { id: 316, label: "Perro de Presa Mallorquin" },
  { id: 317, label: "Peruvian Hairless Dog" },
  { id: 318, label: "Petit Basset Griffon Vendéen" },
  { id: 319, label: "Petit Bleu de Gascogne" },
  { id: 320, label: "Phalène" },
  { id: 321, label: "Pharaoh Hound" },
  { id: 322, label: "Phu Quoc ridgeback dog" },
  { id: 323, label: "Picardy Spaniel" },
  { id: 324, label: "Plott Hound" },
  { id: 325, label: "Podenco Canario" },
  { id: 326, label: "Pointer (dog breed)" },
  { id: 327, label: "Polish Greyhound" },
  { id: 328, label: "Polish Hound" },
  { id: 329, label: "Polish Hunting Dog" },
  { id: 330, label: "Polish Lowland Sheepdog" },
  { id: 331, label: "Polish Tatra Sheepdog" },
  { id: 332, label: "Pomeranian" },
  { id: 333, label: "Pont-Audemer Spaniel" },
  { id: 334, label: "Poodle" },
  { id: 335, label: "Porcelaine" },
  { id: 336, label: "Portuguese Podengo" },
  { id: 337, label: "Portuguese Pointer" },
  { id: 338, label: "Portuguese Water Dog" },
  { id: 339, label: "Posavac Hound" },
  { id: 340, label: "Pražský Krysařík" },
  { id: 341, label: "Pudelpointer" },
  { id: 342, label: "Pug" },
  { id: 343, label: "Puli" },
  { id: 344, label: "Pumi" },
  { id: 345, label: "Pungsan Dog" },
  { id: 346, label: "Pyrenean Mastiff" },
  { id: 347, label: "Pyrenean Shepherd" },
  { id: 348, label: "Rafeiro do Alentejo" },
  { id: 349, label: "Rajapalayam" },
  { id: 350, label: "Rampur Greyhound" },
  { id: 351, label: "Rastreador Brasileiro" },
  { id: 352, label: "Rat Terrier" },
  { id: 353, label: "Ratonero Bodeguero Andaluz" },
  { id: 354, label: "Redbone Coonhound" },
  { id: 355, label: "Rhodesian Ridgeback" },
  { id: 356, label: "Rottweiler" },
  { id: 357, label: "Rough Collie" },
  { id: 358, label: "Russell Terrier" },
  { id: 359, label: "Russian Spaniel" },
  { id: 360, label: "Russian tracker" },
  { id: 361, label: "Russo-European Laika" },
  { id: 362, label: "Sabueso Español" },
  { id: 363, label: "Saint-Usuge Spaniel" },
  { id: 364, label: "Sakhalin Husky" },
  { id: 365, label: "Saluki" },
  { id: 366, label: "Samoyed" },
  { id: 367, label: "Sapsali" },
  { id: 368, label: "Schapendoes" },
  { id: 369, label: "Schillerstövare" },
  { id: 370, label: "Schipperke" },
  { id: 371, label: "Schweizer Laufhund" },
  { id: 372, label: "Schweizerischer Niederlaufhund" },
  { id: 373, label: "Scotch Collie" },
  { id: 374, label: "Scottish Deerhound" },
  { id: 375, label: "Scottish Terrier" },
  { id: 376, label: "Sealyham Terrier" },
  { id: 377, label: "Segugio Italiano" },
  { id: 378, label: "Seppala Siberian Sleddog" },
  { id: 379, label: "Serbian Hound" },
  { id: 380, label: "Serbian Tricolour Hound" },
  { id: 381, label: "Shar Pei" },
  { id: 382, label: "Shetland Sheepdog" },
  { id: 383, label: "Shiba Inu" },
  { id: 384, label: "Shih Tzu" },
  { id: 385, label: "Shikoku" },
  { id: 386, label: "Shiloh Shepherd Dog" },
  { id: 387, label: "Siberian Husky" },
  { id: 388, label: "Silken Windhound" },
  { id: 389, label: "Sinhala Hound" },
  { id: 390, label: "Skye Terrier" },
  { id: 391, label: "Sloughi" },
  { id: 392, label: "Slovak Cuvac" },
  { id: 393, label: "Slovakian Rough-haired Pointer" },
  { id: 394, label: "Small Greek Domestic Dog" },
  { id: 395, label: "Small Münsterländer" },
  { id: 396, label: "Smooth Collie" },
  { id: 397, label: "South Russian Ovcharka" },
  { id: 398, label: "Southern Hound" },
  { id: 399, label: "Spanish Mastiff" },
  { id: 400, label: "Spanish Water Dog" },
  { id: 401, label: "Spinone Italiano" },
  { id: 402, label: "Sporting Lucas Terrier" },
  { id: 403, label: "St. Bernard" },
  { id: 404, label: "St. John's water dog" },
  { id: 405, label: "Stabyhoun" },
  { id: 406, label: "Staffordshire Bull Terrier" },
  { id: 407, label: "Standard Schnauzer" },
  { id: 408, label: "Stephens Cur" },
  { id: 409, label: "Styrian Coarse-haired Hound" },
  { id: 410, label: "Sussex Spaniel" },
  { id: 411, label: "Swedish Lapphund" },
  { id: 412, label: "Swedish Vallhund" },
  { id: 413, label: "Tahltan Bear Dog" },
  { id: 414, label: "Taigan" },
  { id: 415, label: "Talbot" },
  { id: 416, label: "Tamaskan Dog" },
  { id: 417, label: "Teddy Roosevelt Terrier" },
  { id: 418, label: "Telomian" },
  { id: 419, label: "Tenterfield Terrier" },
  { id: 420, label: "Thai Bangkaew Dog" },
  { id: 421, label: "Thai Ridgeback" },
  { id: 422, label: "Tibetan Mastiff" },
  { id: 423, label: "Tibetan Spaniel" },
  { id: 424, label: "Tibetan Terrier" },
  { id: 425, label: "Tornjak" },
  { id: 426, label: "Tosa" },
  { id: 427, label: "Toy Bulldog" },
  { id: 428, label: "Toy Fox Terrier" },
  { id: 429, label: "Toy Manchester Terrier" },
  { id: 430, label: "Toy Trawler Spaniel" },
  { id: 431, label: "Transylvanian Hound" },
  { id: 432, label: "Treeing Cur" },
  { id: 433, label: "Treeing Walker Coonhound" },
  { id: 434, label: "Trigg Hound" },
  { id: 435, label: "Tweed Water Spaniel" },
  { id: 436, label: "Tyrolean Hound" },
  { id: 437, label: "Vizsla" },
  { id: 438, label: "Volpino Italiano" },
  { id: 439, label: "Weimaraner" },
  { id: 440, label: "Welsh Sheepdog" },
  { id: 441, label: "Welsh Springer Spaniel" },
  { id: 442, label: "Welsh Terrier" },
  { id: 443, label: "West Highland White Terrier" },
  { id: 444, label: "West Siberian Laika" },
  { id: 445, label: "Westphalian Dachsbracke" },
  { id: 446, label: "Wetterhoun" },
  { id: 447, label: "Whippet" },
  { id: 448, label: "White Shepherd" },
  { id: 449, label: "Wire Fox Terrier" },
  { id: 450, label: "Wirehaired Pointing Griffon" },
  { id: 451, label: "Wirehaired Vizsla" },
  { id: 452, label: "Yorkshire Terrier" },
  { id: 453, label: "Šarplaninac" },
];
