const Strings = {
  myAccount: "My Account",
  myBookings: "My Bookings",
  clientReviews: "Client Reviews",
  paymentSubScription: "Payments & Subscription",
  myProfile: "My Profile",
  registerAsParent: "Register as a Pet Parent",
  refundCancellationPolicy: "Refund & Cancellation Policy",
  privacyPolicy: "Privacy Policy",
  deleteAccount: "Delete Account",
  logout: "Log Out",
  premiumMemmber: "Premium Member",
  guestUser: "Guest User",
  guest: "Guest",
  businessDetails: "Business details",
  businessDescription: "Name, Role, Services, Experience",
  contactDescription: "Phone number, Email ID, Address",
  uploadImages: "Uploaded images & documents",
  uploadImagesDescription: "Place images, Certificates, Logo etc.",
  sessionDetails: "Session details",
  sessionDescriptions: "Time, charges, Home visit, Holiday",
  mediaLinks: "Media Links",
  mediaDescription: "Social media & Webiste",
  markHoliday: "Mark Holiday",
  contactUs: "Contact Us",
  aboutUs: "About Us",
  addLink: "Add link",
  fbLink: "Facebook: Link",
  pasteLink: "Paste Link",
  websiteLink: "Website: Link",
  instaLink: "Insta link",
  submit: "Submit",
  socialMediaLink: "Social Media Link",
  onlineConsultation: "Online Consultation",
  mobileNo: "Mobile Number*",
  enterMobileNo: "Enter mobile number",
  emailId: "Email Id*",
  enterEmailId: "Enter email id",
  address: "Address*",
  enterAddress: "Enter Address*",
  location: "Location name as per API available*",
  enterLocation: "Enter Location",
  postalCode: "Postal code",
  enterPostalCode: "Enter postal code*",
  contactDetails: "Contact Details",
  uploadImagesDoc: "Uploaded Images & Documents",
  businessLogo: "Business Logo",
  add: "Add +",
  businessPlaceImages: "Business place images",
  certificationDocuments: "Certification/Supportive Documents",
  pleaseAddLogo: "Please add your logo",
  pleaseAddImg: "Please add your images",
  howYouWillBeAvailable: "How you will be available*",
  perSessionCharges: "Per session details",
  chargesPerSession: "Charges per Session (In Rupee)*",
  enterPrice: "Enter price",
  perDaySessionInMin: "Per day session time (In min)*",
  perDaySession: "Enter per day session",
  perMonthSession: "Per month session details",
  paymentDetails: "Payments details",
  workingDays: "Working Days*",
  workingTime: "Working Time*",
  fullDay: "Full Day",
  twoShiftInADay: "Two Shifts in a Day",
  selectTime: "Select Time*",
  sameTimeForDay: "Same time for all days",
  firstHalf: "First Half",
  secondHalf: "Second Half",
  start: "Start",
  close: "Close",
  transactionId: "Transaction ID",
  amount: "Amount",
  paymentMode: "Payment mode",
  subscriptionPeriod: "Subscription period",
  payNow: "Pay Now",
  joinTheFun: "Join the Fun! Subscribe Now!",
  months: "Months",
  unlockPremiumFeature: "Unlock Premium Features!",
  subscriptionCost: " Subscription Cost",
  viewBreakup: "View Breakup",
  tax: "Tax",
  total: "Total",
  thankYouFor: "Thank You for",
  subscriping: "Subscribing! 🎉",
  successfulSubscription:
    " Welcome to the family! Get ready to enjoy all the exclusive features and benefits we have in store for you. Happy exploring!",
  subscriptionValidation:
    " Your subscription will be valid till (Actual valid date) 20/12/2025",
  upgradeSubscription: "Upgrade Subscription",
  hadWonderFulExperience:
    "Had a wonderful experience with Ket! Extremely wise trainer.",
  comments: "Comments*",
  enterYourCommentHere: "Enter your comments here",
  reply: "Reply",
  edit: "Edit",
  appointments: "Appointments",
  cancelAppointment: "Cancel appointment",
  writeAMessage: "Write message to the client for the cancelation reason.",
  writeAMessageForReschedule:
    "Write message to the client for the rescheduling reason.",
  rescheduleAppointment: "Reschedule Appointment",
  sendRequest: "Send request",
  to: "To",
  from: "From",
  am: "AM",
  pm: "PM",
  hhmm: "HH:MM",
  ddMMYYYY: "DD/MM/YYYY",
  selectDate: "Select Date*",
  selectDate2: "Select Date",
  trendingTopics: "Trending Topics",
  newTopic: "New Topic",
  subject: "Subject*",
  pleaseEnterSubject: "Please enter subject",
  writeBlog: "Write your blog here*",
  writeHere: "Write here",
  uploadCoverImg: "Upload cover image*",
  browse: "Browse",
  selectImg: "Select Image",
  mobileNoEmail: "Mobile number/Email ID",
  entermobileEmail: "Enter your Mobile Number / Email ID",
  signIn: "Sign in or Sign up",
  signWithOtp: "Sign in with OTP",
  skip: "Skip",
  petAdoption: "Pet Adoption",
  businessDetail: "Business details",
  next: "Next",
  myPetProfile: "My Pet Profile",
  paymentError:
    "Your payment is not completed. Please complete payment to access full potential of the app",
  paymentErrorForAdoption:
    "Hey, To get details of Pet please get subcription plan",
  appointmentError:
    "Complete your Registration and Subscribe to the app to create new appointments.",
  approvaltError:
    "Your profile is under verification. Please wait for approval",
  profileError: "Your profile is incomplete. Please complete your registration",
  approvaltErrorForDashboard:
    "Complete your Registration and Subscribe to the app to create new appointments.",
  attention: "Attention!",
  clear: "Clear",
  services: "Services",
  oneSession: "One Session",
  dailySession: "Daily Session",
  startDate: "Start Date",
  endDate: "End Date",
  areYouSure: "Are you sure?",
  confirmAppointmentMessage:
    "Are you sure you want to confirm this appointment?",
  welcome: "Welcome",
  experienced: "Experienced",
  allInOne: "Your All-In-One",
  introText2: "& Hand-Picked Professionals",
  introText3: "Pet Care Hub",
  introDes1:
    "We're dedicated to providing top-priority, personalized care for you and your beloved pet with the highest level of professionalism.",
  introDes2:
    "Our expert, hand-picked team ensures the best care for your pet. Trust us for their well-being and happiness.",
  introDes3:
    "Effortlessly connect with top pet professionals—all in one place, just a tap away!",
  goToDashboard: "Let's Go",
  longHoliday: "Long Holiday",
  end: "End",
  time: "Time",
  holidayError: "Please provide valid data for weekly/long holidays",
  cancelAppointmentsTitle: "✨ Do You Want to Cancel Appointments? ✨",
  cancelAppointmentsDescription:
    "All appointments scheduled on the selected holiday will be automatically canceled.",
  appointmentConfirm: "Appointment has been accepted",
};

export default Strings;
