export const urlList = {
  login: "login/loginWithOTP",
  verifyOTP: "login/VerifyOTP",
  refreshToken: "login/RefreshToken",
  businessDetail: "register/provider/businessdetails",
  contactDetail: "register/provider/contacts",
  mediaLink: "register/provider/medialinks",
  addSession: "register/provider/addsession",
  uploadDocument: "register/provider/adddocument",
  deleteDocument: "register/provider/deletedocument",
  getProfile: "register/getprofile",
  getMasterData: "master/getservices",
  addSessionDetails: "register/provider/addsessiondetails",
  saveSessionCharged: "register/provider/addsessionrates",
};
