const Strings = {
    myAccount:"My Account",
    myBookings:"My Bookings",
    clientReviews:"Client Reviews",
    paymentSubScription:'Payments & Subscription',
    myProfile:"My Profile",
    registerAsParent:"Register as a Pet Parent",
    refundCancellationPolicy:'Refund & Cancellation Policy',
    privacyPolicy:'Privacy Policy',
    deleteAccount:'Delete Account',
    logout:'Log Out',
    premiumMemmber:'Premium Member',
    businessDetails:'Business details',
    businessDescription:'Name, Role, Services, Experience',
    contactDetails:"Contact details",
    contactDescription:'Phone number, Email ID, Address',
    uploadImages:'Uploaded images & documents',
    uploadImagesDescription:'Place images, Certificates, Logo etc.',
    sessionDetails:'Session details',
    sessionDescriptions:'Time, charges, Home visit, Holiday',
    mediaLinks:'Media Links',
    mediaDescription:'Social media & Webiste',
    markHoliday:'Mark Holiday',
    contactUs:"Contact Us",
    aboutUs:"About Us",
    addLink:"Add link",
    pasteLink:"Paste link",
    fbLink:'Facebook: Link',
    pasteLink:"Paste Link",
    websiteLink:'Website: Link',
    instaLink:'Insta link',
    submit:"Submit",
    socialMediaLink:'Social Media Link',
    onlineConsultation:'Online Consultation',
    mobileNo:"Mobile Number*",
    enterMobileNo:"Enter mobile number",
    emailId:"Email Id*",
    enterEmailId:"Enter email id",
    address:"Address",
    enterAddress:'Enter Address',
    location:"Location name as per API available",
    enterLocation:"Enter Location",
    postalCode:"Postal code",
    enterPostalCode:"Enter postal code",
    contactDetails:"Contact Details",
    uploadImagesDoc:"Uploaded Images & Doc",
    businessLogo:"Business Logo",
    add:"Add +",
    businessPlaceImages:'Business place images',
    certificationDocuments:'Certification/Supportive Documents',
    pleaseAddLogo:'Please add your logo',
    pleaseAddImg:'Please add your images',
    howYouWillBeAvailable:'How you will be available*',
    perSessionCharges:'Per Session Charges',
    chargesPerSession:'Charges per Session (In Rupee)*',
    enterPrice:'Enter price',
    perDaySessionInMin:'Per day session time (In min)*',
    perDaySession:'Enter per day session',
    perMonthSession:'Per Month Session Charges',
    paymentDetails:'Payments details',
    workingDays:'Working Days*',
    workingTime:'Working Time*',
    fullDay:'Full Day',
    twoShiftInADay:'Two Shifts in a Day',
    selectTime:'Select Time*',
    sameTimeForDay:'Same time for all day',
    firstHalf:'First Half',
    secondHalf:'Second Half',
    start:'Start',
    close:"Close",
    transactionId:'Transaction ID',
    amount:"Amount",
    paymentMode:"Payment mode",
    subscriptionPeriod:"Subscription period",
    payNow:'Pay Now',
    joinTheFun:'Join the Fun! Subscribe Now!',
    months:'Months',
    unlockPremiumFeature:'Unlock Premium Features!',
    subscriptionCost:" Subscription Cost",
    viewBreakup:'View Breakup',
    tax:"Tax",
    total:'Total',
    thankYouFor:'Thank You for',
    subscriping:'Subscribing! 🎉',
    successfulSubscription:' Welcome to the family! Get ready to enjoy all the exclusive features and benefits we have in store for you. Happy exploring!',
    subscriptionValidation:' Your subscription will be valid till (Actual valid date) 20/12/2025',
    upgradeSubscription:'Upgrade Subscription',
    hadWonderFulExperience:'Had a wonderful experience with Ket! Extremely wise trainer.',
    comments:'Comments*',
    enterYourCommentHere:'Enter your comments here',
    reply:'Reply',
    edit:'Edit'
}

export default Strings